@startuml
title 智能推荐作业流程
start
note left
    针对线上课，正式课
    产品开关打开
end note
: 老师给学生上课完成后;
  partition 智能推荐 {
    if(添加过题目到作业)  then(有课中 paper_id，前端缓存此原始 paper_id)
        :  1. 代理 教研后台 生成作业的接口（返回paper_id)
          2. 代理请求 trresearchsvc 获取作业paper的基础信息接口
          3. 前端缓存 生成的 paper_id;
    else(没有课中 paper_id)
         :  1. 代理 教研后台 生成作业的接口（返回paper_id)
           2. 代理请求 trresearchsvc 获取作业paper的基础信息接口
           3. 前端缓存 生成 paper_id;
    endif
  }
:由智能推荐作业 切换到 题库布置作业;
partition 题库布置 {
if(添加过题目到作业)  then(有课中 paper_id，前端缓存此原始 paper_id)
        :1.智能推荐作业会根据此paper_id中的题目进行推荐,所以复制一份作业（返回paper_id）
        2.代理请求 trresearchsvc 获取作业paper的基础信息接口;
    else(没有课中 paper_id)
         :1.线上原逻辑，点击去题库按钮获取生成一份作业
         2.前端缓存 paper_id;
    endif
  }
:预览并编辑按钮，不能获取课中paper_id的编辑地址，必须获取后续生成的paper_id;
end

@enduml