@startuml
autonumber
title 教研云动态课件回调 --- 课件库
教研云 -> liveteaching: 老师编辑完成，后回调liveteaching
note right:入参携带加密的 onshelf_id
liveteaching -> liveteaching:通过入参判断三种场景
liveteaching -> liveteaching: 新建场景,只有media_id
liveteaching -> liveteaching: 我的课件,有media_id,reference_id
liveteaching -> liveteaching: 课件库,有media_id,onshelf_id
liveteaching -> courseware:  PT 保存编辑的教研云课件
courseware -> courseware:解密 onshelf_id ，找到之前绑定的 courseware_id,拿到之前底层课件的信息
courseware -> courseware:复制老的课件信息，在原有属性上，在 repository 插入一条新纪录，主要更新了 新的 mediaId、页码等
courseware -> courseware:保存链路信息
liveteaching <- courseware:返回新增的 courseware_id
liveteaching -> liveteaching:封装参数，插入一条记录到 reference 表,与 courseware_id,media_id绑定,status = finish
教研云 <- liveteaching:返回 reference_id
@enduml