@startuml
autonumber
title 教研云静态课件回调 --- 课件库场景
H5 -> liveteaching: 老师编辑完成，后回调liveteaching
note right:新加前端缓存的 onshelf_id
liveteaching -> liveteaching:通过入参判断三种场景
liveteaching -> liveteaching: 新建场景,只有media_id
liveteaching -> liveteaching: 我的课件,有media_id,reference_id
liveteaching -> liveteaching: 课件库,有media_id,onshelf_id
liveteaching -> courseware:  PT 保存教研云静态课件接口
courseware -> courseware:通过 media_id 查询 repository 库，如果有记录则报错
courseware -> courseware:调用教研云获取paper中的试题信息（不含段落）paper/getCloudPaperInforById.json
courseware -> courseware:封装参数，主要是 media_id、courseware_name,插入一条纪律到 repository 表
courseware -> courseware:保存链路信息
liveteaching <- courseware:返回新增的 courseware_id
liveteaching -> liveteaching:封装参数，插入一条记录到 reference 表,与 courseware_id,media_id绑定,status = finish
H5 <- liveteaching:返回 reference_id
@enduml