
@startuml
title 成长值获取场景-查看回放（接口）

alt
actor 学生

alt 课后查看课程回放
学生 -> 学生端: 点击"查看回放"
学生端 -> livebff: 客户端计算观看时长达标后，调用pt接口触发成长值增加事件
livebff -> livesvc: 调用pbff接口触发成长值增加事件
livesvc -> livesvc: 校验用户/课程关系
livesvc -> api服务: 校验通过则调用pi接口为用户增加成长值
api服务 -> livesvc: response
livesvc -> 学生端: response
end

@enduml