
@startuml
title 成长值获取场景-课后作业得分优秀（接口）

alt

actor 老师

alt 课后作业得分优秀
老师 -> 老师端: 批改完成学生作业
老师端 -> api服务: 老师批改作业流程（或自动批改流程）
api服务 -> api服务: 成绩优秀则触发成长值增加事件
note right
    批改作业流程由api确认
end note
api服务 -> 学生端: 学生作业成绩优秀则通知学生端
学生端 -> 学生端: 在线则弹框提示
end

@enduml