@startuml
title 商品中台接入类目中台获取可使用品类
autonumber
actor 商品前端
participant 100015128
participant 100019933
participant 100015009
participant 100020650

商品前端->100015128: getCurrentUser，获取当前登录用户接口，此接口返回可使用类目
100015128 ->100019933: categoryQuery，获取类目中台品类列表
100019933 ->100015128: 返回类目中台品类列表
note left: categoryQuery 接口响应中的 tourCategoryId 字段为类目中台品类id
100015128 -> 100015009: GetProviderCategoryToB ，根据供应商id查询该供应商可使用品类
100015009 -> 100015128: 返回该供应商对于品类的权限问题，根据status字段区分为以下三种情况
100015128-> 商品前端:return

alt status 为 direct 时，表示该品类可以直接使用
商品前端 -> 商品前端: case 1：处理可直接使用类目
note right: 前端直接展示即可
end

alt status 为 noPermission 时，表示该品类无权限【资质到期或无资质】
商品前端 -> 商品前端: case 2：处理资质到期或无资质的类目
note right: 前端获取该品类对象中返回的url链接直接跳转
end

alt status 为 noPermissionButApply 时，表示该品类无权限需供应商手动申请
商品前端 -> 商品前端: case 3：处理需要申请权限的品类
note right: 前端获取该品类对象中返回的 piCategoryId 字段，调用 SaveProviderCategoryConfig
商品前端 -> 100020650: 前端根据调用100020650应用的 SaveProviderCategoryConfig 接口申请权限，并展示
100020650 -> 商品前端: return
end
@enduml