@startuml
autonumber
title 首课跟进&备课4.0 时序图
H5 -> livesvc: 首课备课按钮
note right:调用api接口获取首课备课任务完成状态
livesvc -> fullcrm: 调用fullcrm获取学生详细信息
fullcrm -> livesvc: 返回学生详细信息
livesvc -> H5: 展示完整的学生数据
H5 -> livesvc: 编辑按钮
livesvc -> fullcrm: 保存老师编辑后的信息
livesvc -> livesvc: 点击确认下一步按钮
livesvc -> api: 通知api已完成首课备课


@enduml