@startuml
autonumber
title 图片转码时序图
livedew -> livedes: 调用 get_pic_encoding_task 获取图片转码任务
note right:livedes/api/{livedew|}pt/v2/image/apply_video_upload
livedes -> fullcrm: 调用fullcrm，获取学生详细信息
fullcrm -> livedes: 返回学生详细信息
livedes -> livedew: 展示完整的学生数据
livedew -> livedes: 编辑页面，保存按钮
livedes -> fullcrm: 调用fullcrm，更新老师编辑后的学生信息
livedew -> livedes: 点击确认下一步按钮
livedes -> api: 调用api已完成首课备课
@enduml